package day08

import (
	"testing"

	"github.com/maxnoe/adventofcode2024/aoc24"
)

var test_input = `
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`

func TestPart1(t *testing.T) {
	world, _ := Parse(test_input)
	res, _ := Part1(world)
	aoc24.AssertEqual(t, res, 14)
}

func TestPart2(t *testing.T) {
	world, _ := Parse(test_input)
	res, _ := Part2(world)
	aoc24.AssertEqual(t, res, 34)
}
